### ISSUE TITLE
ccs811.begin（）failed

### ISSUE THREAD

**Issue by hassbian-ABC** [yoggy/mqtt-ccs811-pub#1]
![5y 0pyvgme1 7iwkkszj](https://user-images.githubusercontent.com/37896214/51436534-1dc60900-1cca-11e9-9285-63dfcf26bfa1.png)

**Comment by yoggy** [comment]
Please check your wiring, and I2C address of your CCS811.
(in this sketch, "#define CCS811_ADDR 0x5B")
